### ISSUE TITLE
Image not loading properly

### ISSUE THREAD

**Issue by Floge123** [malthee/Hiromaji#13]
![image](https://github.com/malthee/Hiromaji/assets/80892353/dabe6dcf-88c6-47a3-9703-c7c66f4a3163)

**Comment by malthee** [comment]
common issue, follow the instructions of this guide:

![detailed guide to fix problem of yours](https://github.com/malthee/Hiromaji/assets/18032233/e53a8d10-60b5-406c-898c-dd3ac4bcdc91)
